// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQd8OElcJ8KQGT59fxfSIlXm_-R2SMmU',
    appId: '1:328450857297:android:21319a96f2ab1e8d529b70',
    messagingSenderId: '328450857297',
    projectId: 'gaia-pose-analysis',
    databaseURL: 'https://gaia-pose-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'gaia-pose-analysis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqy3nK4PrbL2riN6FkMX-jYt7F3fBeAj0',
    appId: '1:328450857297:ios:de05a9ce5a37662f529b70',
    messagingSenderId: '328450857297',
    projectId: 'gaia-pose-analysis',
    databaseURL: 'https://gaia-pose-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'gaia-pose-analysis.firebasestorage.app',
    iosBundleId: 'com.example.poseDetectionRealtime',
  );
}
